/**
 * The Lucide and Game Icons drawings the app uses, through Iconify. Add a name here, then run `pnpm icons` to copy
 * its drawing into `lucide.generated.ts`: only these are bundled, and nothing is fetched at run
 * time (the CSP allows no request to Iconify's API). Names: https://icon-sets.iconify.design/; Game Icons use the game-icons: prefix.
 */
export const ICON_NAMES = [
  'game-icons:tabletop-players',
  'game-icons:dungeon-gate',
  'game-icons:meeple',
  'game-icons:scroll-quill',
  'game-icons:exit-door',
  'calendar',
  'circle-x',
  'user-plus',
  'user-check',
  'user-x',
  'user-minus',
  'star',
  'tag',
  'shield',
  'megaphone',
  'wrench',
  'triangle-alert',
  'sparkles',
  'gift',
  'info',
  'chevron-down',
  'users',
  'dices',
  'flag',
  'refresh-cw',
  'arrow-right',
  'external-link',
  'search',
  'chevron-left',
  'chevron-right',
  'message-circle',
  'send',
  'bell-off',
  'bell',
  'arrow-left',
  'plus',
  'layout-grid',
  'panel-left-open',
  'panel-left-close',
  'bold',
  'italic',
  'underline',
  'strikethrough',
  'heading-2',
  'heading-3',
  'list',
  'list-ordered',
  'quote',
  'code',
  'minus',
  'link',
  'unlink',
  'undo-2',
  'redo-2',
  'instagram',
] as const;

export type IconName = (typeof ICON_NAMES)[number];
