-- The 682 RPG systems the tables are categorised by, in the order of the source list (most played
-- first, then A to Z). Names are stored exactly as written; each slug comes from slugify(), with -2, -3
-- added on a collision (Cy_borg and CY_BORG differ only in case). Slugs are stable from here on: to add
-- a system, write a new migration. ON CONFLICT makes re-running the insert harmless.
CREATE TABLE "systems" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" text NOT NULL,
	"slug" text NOT NULL,
	"position" integer NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "systems_slug_unique" ON "systems" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "systems_name_unique" ON "systems" USING btree ("name");--> statement-breakpoint
INSERT INTO "systems" ("name", "slug", "position") VALUES
	('Dungeons & Dragons 5.5e (2024)', 'dungeons-e-dragons-5-5e-2024', 1),
	('Dungeons & Dragons 5e (2014)', 'dungeons-e-dragons-5e-2014', 2),
	('Tormenta 20 (T20)', 'tormenta-20-t20', 3),
	('Daggerheart', 'daggerheart', 4),
	('Chamado de Cthulhu', 'chamado-de-cthulhu', 5),
	(':Otherscape', 'otherscape', 6),
	('+2d6', '2d6', 7),
	('13th Age', '13th-age', 8),
	('2077 Distopia Cybernética', '2077-distopia-cybernetica', 9),
	('3D&T', '3dt', 10),
	('3D&T Victory', '3dt-victory', 11),
	('4d6', '4d6', 12),
	('7th Sea', '7th-sea', 13),
	('A Bandeira do Elefante e da Arara', 'a-bandeira-do-elefante-e-da-arara', 14),
	('A Familiar Problem', 'a-familiar-problem', 15),
	('A Fita', 'a-fita', 16),
	('A Hora de Aventura - Roleplaying Game', 'a-hora-de-aventura-roleplaying-game', 17),
	('A Lenda de Ghanor RPG', 'a-lenda-de-ghanor-rpg', 18),
	('A Ordem dos Últimos', 'a-ordem-dos-ultimos', 19),
	('A Song of Ice and Fire RPG', 'a-song-of-ice-and-fire-rpg', 20),
	('A Trupe', 'a-trupe', 21),
	('Aberrant', 'aberrant', 22),
	('Abismo Infinito', 'abismo-infinito', 23),
	('Absurdia', 'absurdia', 24),
	('Academia Arcana', 'academia-arcana', 25),
	('Aces & Eights Reloaded', 'aces-e-eights-reloaded', 26),
	('Achtung! Cthulhu 2d20', 'achtung-cthulhu-2d20', 27),
	('Action Movie World', 'action-movie-world', 28),
	('Advanced Dungeons & Dragons 1e', 'advanced-dungeons-e-dragons-1e', 29),
	('Advanced Dungeons & Dragons 2e', 'advanced-dungeons-e-dragons-2e', 30),
	('Adventure Skeletons', 'adventure-skeletons', 31),
	('Adventurer Conqueror King', 'adventurer-conqueror-king', 32),
	('Adventures in Middle-earth', 'adventures-in-middle-earth', 33),
	('Afterlife: Wandering Souls', 'afterlife-wandering-souls', 34),
	('Age of Adventure', 'age-of-adventure', 35),
	('Age of Sigmar Soulbound', 'age-of-sigmar-soulbound', 36),
	('Age of Vikings', 'age-of-vikings', 37),
	('Agon', 'agon', 38),
	('Alice is Missing', 'alice-is-missing', 39),
	('Alien: The Roleplaying Game', 'alien-the-roleplaying-game', 40),
	('All Flesh Must Be Eaten', 'all-flesh-must-be-eaten', 41),
	('Amber Diceless', 'amber-diceless', 42),
	('Amigo Dragão', 'amigo-dragao', 43),
	('An Exquisite Crime', 'an-exquisite-crime', 44),
	('Anansi', 'anansi', 45),
	('Anima Beyond Fantasy', 'anima-beyond-fantasy', 46),
	('Anime 5e', 'anime-5e', 47),
	('Anime e Sangue', 'anime-e-sangue', 48),
	('Antagonist', 'antagonist', 49),
	('Apocalypse Keys', 'apocalypse-keys', 50),
	('Apocalypse World 2e', 'apocalypse-world-2e', 51),
	('Arcana Primária', 'arcana-primaria', 52),
	('Arkanun', 'arkanun', 53),
	('Arkham Horror', 'arkham-horror', 54),
	('Arquivos Paranormais', 'arquivos-paranormais', 55),
	('Ars Magica Fifth Edition', 'ars-magica-fifth-edition', 56),
	('As 7 Baladas do Oeste', 'as-7-baladas-do-oeste', 57),
	('As Chaves da Torre', 'as-chaves-da-torre', 58),
	('Ashen Stars', 'ashen-stars', 59),
	('Ashes of Tomorrow', 'ashes-of-tomorrow', 60),
	('Ashes Without Number', 'ashes-without-number', 61),
	('Assassin''s Creed RPG', 'assassins-creed-rpg', 62),
	('Assimilação', 'assimilacao', 63),
	('Assimilação RPG', 'assimilacao-rpg', 64),
	('Áureos: Os Dançarinos da Lua', 'aureos-os-dancarinos-da-lua', 65),
	('Avatar Legends: The RPG', 'avatar-legends-the-rpg', 66),
	('Aventuras Lendárias', 'aventuras-lendarias', 67),
	('Babes in the Woods', 'babes-in-the-woods', 68),
	('Badge Quest', 'badge-quest', 69),
	('Band of Blades', 'band-of-blades', 70),
	('Bárbaros da Lemúria', 'barbaros-da-lemuria', 71),
	('BASIC Fantasy', 'basic-fantasy', 72),
	('Basic Roleplaying', 'basic-roleplaying', 73),
	('BattleTech RPG', 'battletech-rpg', 74),
	('Beacon', 'beacon', 75),
	('Beam Saber', 'beam-saber', 76),
	('Belregard', 'belregard', 77),
	('BEOWULF: Age of Heroes', 'beowulf-age-of-heroes', 78),
	('Berserkr', 'berserkr', 79),
	('Better Angels', 'better-angels', 80),
	('Between Clouds', 'between-clouds', 81),
	('Beyond The Wall and Other Adventures', 'beyond-the-wall-and-other-adventures', 82),
	('Big Eyes, Small Mouth', 'big-eyes-small-mouth', 83),
	('Birthright', 'birthright', 84),
	('Bite Marks', 'bite-marks', 85),
	('Black Crusade', 'black-crusade', 86),
	('Blade Runner: The Roleplaying Game', 'blade-runner-the-roleplaying-game', 87),
	('Blades in the Dark', 'blades-in-the-dark', 88),
	('Blood, Sweat & Steel', 'blood-sweat-e-steel', 89),
	('Bluebeard''s Bride', 'bluebeards-bride', 90),
	('Boot Hill', 'boot-hill', 91),
	('Brancalônia', 'brancalonia', 92),
	('Brave Zenith', 'brave-zenith', 93),
	('BREAK!!', 'break', 94),
	('BREU', 'breu', 95),
	('Brindlewood Bay', 'brindlewood-bay', 96),
	('Brinkwood: The Blood of Tyrants', 'brinkwood-the-blood-of-tyrants', 97),
	('Broken Compass', 'broken-compass', 98),
	('Brumas de Nivellon', 'brumas-de-nivellon', 99),
	('Brutal RPG', 'brutal-rpg', 100),
	('Bruxo: Pacto das Sombras', 'bruxo-pacto-das-sombras', 101),
	('Bunkers & Badasses', 'bunkers-e-badasses', 102),
	('Bunnies & Burrows', 'bunnies-e-burrows', 103),
	('Burn Bryte', 'burn-bryte', 104),
	('By the Sword', 'by-the-sword', 105),
	('Caçada sem Luar', 'cacada-sem-luar', 106),
	('Caçador: A Revanche', 'cacador-a-revanche', 107),
	('Caçador: A Vigília', 'cacador-a-vigilia', 108),
	('Cagueta', 'cagueta', 109),
	('CAIN', 'cain', 110),
	('Cairn', 'cairn', 111),
	('Cairn 2e', 'cairn-2e', 112),
	('Caltrop Core', 'caltrop-core', 113),
	('Candela Obscura', 'candela-obscura', 114),
	('Cangaço Trevoso', 'cangaco-trevoso', 115),
	('Capers', 'capers', 116),
	('Capes, Cowls and Villains Foul', 'capes-cowls-and-villains-foul', 117),
	('Carbon 2185', 'carbon-2185', 118),
	('Carbon Grey', 'carbon-grey', 119),
	('Casos Conspiratórios', 'casos-conspiratorios', 120),
	('Castle Falkenstein', 'castle-falkenstein', 121),
	('Castles & Crusades', 'castles-e-crusades', 122),
	('Caves and Hexes', 'caves-and-hexes', 123),
	('CBR+PNK', 'cbr-pnk', 124),
	('Centavos Macabros', 'centavos-macabros', 125),
	('Changeling: The Dreaming 20th Anniversary Edition', 'changeling-the-dreaming-20th-anniversary-edition', 126),
	('Changeling: The Lost Second Edition', 'changeling-the-lost-second-edition', 127),
	('Charge RPG', 'charge-rpg', 128),
	('Chrome', 'chrome', 129),
	('Chronicles of Darkness', 'chronicles-of-darkness', 130),
	('City of Mist', 'city-of-mist', 131),
	('Cloudbreaker Alliance', 'cloudbreaker-alliance', 132),
	('Cogent Roleplay', 'cogent-roleplay', 133),
	('Colônia RPG', 'colonia-rpg', 134),
	('Conan', 'conan', 135),
	('Conan: Adventures in an Age Undreamed Of', 'conan-adventures-in-an-age-undreamed-of', 136),
	('Conspirações RPG', 'conspiracoes-rpg', 137),
	('Cordel do Reino do Sol Encantado', 'cordel-do-reino-do-sol-encantado', 138),
	('Corespring RPG', 'corespring-rpg', 139),
	('Coriolis - The Third Horizon', 'coriolis-the-third-horizon', 140),
	('Coriolis: The Great Dark', 'coriolis-the-great-dark', 141),
	('Cornucopia Adventurers'' Guild', 'cornucopia-adventurers-guild', 142),
	('Cortex RPG', 'cortex-rpg', 143),
	('Cosa Nostra', 'cosa-nostra', 144),
	('Cosmere Roleplaying Game', 'cosmere-roleplaying-game', 145),
	('Coven & Crucible', 'coven-e-crucible', 146),
	('Coyote & Crow', 'coyote-e-crow', 147),
	('Cthulhu Hack 2e', 'cthulhu-hack-2e', 148),
	('Cultos Inomináveis', 'cultos-inominaveis', 149),
	('Curseborne', 'curseborne', 150),
	('Curso', 'curso', 151),
	('Cy_borg', 'cy-borg', 152),
	('CY_BORG', 'cy-borg-2', 153),
	('Cyberpunk 2020', 'cyberpunk-2020', 154),
	('Cyberpunk Red', 'cyberpunk-red', 155),
	('Cypher System', 'cypher-system', 156),
	('D20 Modern', 'd20-modern', 157),
	('d20 OGL', 'd20-ogl', 158),
	('d20age', 'd20age', 159),
	('D6 System', 'd6-system', 160),
	('Dark Heresy 1e', 'dark-heresy-1e', 161),
	('Dark Heresy 2e', 'dark-heresy-2e', 162),
	('Dark Matter', 'dark-matter', 163),
	('DARK SOULS: The Roleplaying Game', 'dark-souls-the-roleplaying-game', 164),
	('DC Heroes Roleplaying Game', 'dc-heroes-roleplaying-game', 165),
	('DC20', 'dc20', 166),
	('Dead of Night', 'dead-of-night', 167),
	('Deadlands', 'deadlands', 168),
	('Death in Space', 'death-in-space', 169),
	('Deathmatch Island', 'deathmatch-island', 170),
	('Deathwatch', 'deathwatch', 171),
	('Defensores de Tóquio (OD&T)', 'defensores-de-toquio-odt', 172),
	('Defiant O Despertar', 'defiant-o-despertar', 173),
	('Definitely Wizards', 'definitely-wizards', 174),
	('Déloyal', 'deloyal', 175),
	('Delta Green', 'delta-green', 176),
	('Demon Gate', 'demon-gate', 177),
	('Demon Ninja', 'demon-ninja', 178),
	('Demônio: A Queda', 'demonio-a-queda', 179),
	('Destino Obscuro', 'destino-obscuro', 180),
	('DIE RPG', 'die-rpg', 181),
	('Discworld', 'discworld', 182),
	('Dishonored', 'dishonored', 183),
	('Distopia RPG', 'distopia-rpg', 184),
	('Doctor Who RPG', 'doctor-who-rpg', 185),
	('Dominus', 'dominus', 186),
	('Don''t Kill A Bird With A Baseball', 'dont-kill-a-bird-with-a-baseball', 187),
	('Dorama RPG', 'dorama-rpg', 188),
	('Dragon Age', 'dragon-age', 189),
	('Dragonbane', 'dragonbane', 190),
	('DramaSystem', 'dramasystem', 191),
	('Draw Steel', 'draw-steel', 192),
	('Dresden Files Accelerated Edition', 'dresden-files-accelerated-edition', 193),
	('DUMP Quest', 'dump-quest', 194),
	('Dune: Adventures in the Imperium', 'dune-adventures-in-the-imperium', 195),
	('Dungeon Crawl Classics', 'dungeon-crawl-classics', 196),
	('Dungeon World', 'dungeon-world', 197),
	('Dungeon! Board Game', 'dungeon-board-game', 198),
	('Dungeons & Dragons 0e', 'dungeons-e-dragons-0e', 199),
	('Dungeons & Dragons 1e', 'dungeons-e-dragons-1e', 200),
	('Dungeons & Dragons 2e', 'dungeons-e-dragons-2e', 201),
	('Dungeons & Dragons 3/3.5e', 'dungeons-e-dragons-3-3-5e', 202),
	('Dungeons & Dragons 4e', 'dungeons-e-dragons-4e', 203),
	('Dungeons & Dragons B/X', 'dungeons-e-dragons-b-x', 204),
	('Dusk City Outlaws', 'dusk-city-outlaws', 205),
	('Earthdawn', 'earthdawn', 206),
	('EAT THE REICH', 'eat-the-reich', 207),
	('Eclipse Phase', 'eclipse-phase', 208),
	('Eldritch Automata', 'eldritch-automata', 209),
	('Eldritch RPG', 'eldritch-rpg', 210),
	('Electric Bastionland', 'electric-bastionland', 211),
	('Elthos RPG', 'elthos-rpg', 212),
	('Empire of the Petal Throne', 'empire-of-the-petal-throne', 213),
	('Entity', 'entity', 214),
	('Epifania', 'epifania', 215),
	('Epitaph', 'epitaph', 216),
	('Epyllion', 'epyllion', 217),
	('Era do Caos', 'era-do-caos', 218),
	('Errant RPG', 'errant-rpg', 219),
	('Espadas Afiadas & Feitiços Sombrios', 'espadas-afiadas-e-feiticos-sombrios', 220),
	('Esper Genesis', 'esper-genesis', 221),
	('Este Corpo Mortal', 'este-corpo-mortal', 222),
	('Etmos RPG', 'etmos-rpg', 223),
	('Evento', 'evento', 224),
	('Everyday Heroes', 'everyday-heroes', 225),
	('Exalted 2nd Edition', 'exalted-2nd-edition', 226),
	('Exalted 3rd Edition', 'exalted-3rd-edition', 227),
	('Exalted Essence', 'exalted-essence', 228),
	('Extra Ordinary', 'extra-ordinary', 229),
	('EZD6', 'ezd6', 230),
	('Fablecraft', 'fablecraft', 231),
	('Fabula Ultima', 'fabula-ultima', 232),
	('Fading Suns', 'fading-suns', 233),
	('Fallout: The Roleplaying Game', 'fallout-the-roleplaying-game', 234),
	('FangKnight', 'fangknight', 235),
	('Fantasy AGE RPG', 'fantasy-age-rpg', 236),
	('FATE', 'fate', 237),
	('Fate Accelerated', 'fate-accelerated', 238),
	('Fate Core System', 'fate-core-system', 239),
	('Fate of Cthulhu', 'fate-of-cthulhu', 240),
	('Fear Itself', 'fear-itself', 241),
	('Feng Shui 2', 'feng-shui-2', 242),
	('Fiasco', 'fiasco', 243),
	('Filhos do destino', 'filhos-do-destino', 244),
	('Final Fantasy RPG 4th Edition', 'final-fantasy-rpg-4th-edition', 245),
	('FIST', 'fist', 246),
	('Five Torches Deep', 'five-torches-deep', 247),
	('Fomoria', 'fomoria', 248),
	('For the Dungeon!', 'for-the-dungeon', 249),
	('For The Queen', 'for-the-queen', 250),
	('For the Quest', 'for-the-quest', 251),
	('Forbidden Lands', 'forbidden-lands', 252),
	('Fractal', 'fractal', 253),
	('Fragged Empire', 'fragged-empire', 254),
	('Free Kriegsspiel Revolution', 'free-kriegsspiel-revolution', 255),
	('Frontier Scum', 'frontier-scum', 256),
	('Fudge', 'fudge', 257),
	('Full Metal Cria', 'full-metal-cria', 258),
	('FUNdamental RPG', 'fundamental-rpg', 259),
	('G.I. JOE Roleplaying Game', 'g-i-joe-roleplaying-game', 260),
	('Gaia: O Prelúdio', 'gaia-o-preludio', 261),
	('Game Master Workshop', 'game-master-workshop', 262),
	('Gatunos', 'gatunos', 263),
	('Genesys', 'genesys', 264),
	('Ghostbusters RPG', 'ghostbusters-rpg', 265),
	('Girl by Moonlight', 'girl-by-moonlight', 266),
	('Glitter Hearts', 'glitter-hearts', 267),
	('Gloomhaven', 'gloomhaven', 268),
	('Godbound', 'godbound', 269),
	('Godforsaken', 'godforsaken', 270),
	('Golden Sky Stories', 'golden-sky-stories', 271),
	('Good Society', 'good-society', 272),
	('Grimwild', 'grimwild', 273),
	('Guardiões do Limbo', 'guardioes-do-limbo', 274),
	('Guerra dos Tronos RPG', 'guerra-dos-tronos-rpg', 275),
	('Gumshoe', 'gumshoe', 276),
	('GURPS', 'gurps', 277),
	('Hackmaster', 'hackmaster', 278),
	('Harnmaster', 'harnmaster', 279),
	('Heart: The City Beneath RPG', 'heart-the-city-beneath-rpg', 280),
	('Heckin'' Good Doggos', 'heckin-good-doggos', 281),
	('Herança de Cthulhu', 'heranca-de-cthulhu', 282),
	('HERO System', 'hero-system', 283),
	('Heroes & Hardships', 'heroes-e-hardships', 284),
	('Heroes of Cerulea', 'heroes-of-cerulea', 285),
	('Heróis & Hordas', 'herois-e-hordas', 286),
	('HeroQuest', 'heroquest', 287),
	('Hitos', 'hitos', 288),
	('Hogwarts RPG', 'hogwarts-rpg', 289),
	('Holler', 'holler', 290),
	('Homebrew Game', 'homebrew-game', 291),
	('Honey Heist', 'honey-heist', 292),
	('Hopefinder', 'hopefinder', 293),
	('Horror: A Roleplaying Game', 'horror-a-roleplaying-game', 294),
	('Household', 'household', 295),
	('ICONS Superpowered Roleplaying', 'icons-superpowered-roleplaying', 296),
	('ICRPG Index Card RPG', 'icrpg-index-card-rpg', 297),
	('Impulse Drive', 'impulse-drive', 298),
	('In Nomine', 'in-nomine', 299),
	('Indie TTRPG', 'indie-ttrpg', 300),
	('Inevitable', 'inevitable', 301),
	('Infaernum', 'infaernum', 302),
	('Infinity', 'infinity', 303),
	('Intergalactica', 'intergalactica', 304),
	('Interstitial: Our Hearts Intertwined', 'interstitial-our-hearts-intertwined', 305),
	('Into the Madness', 'into-the-madness', 306),
	('Into the Odd', 'into-the-odd', 307),
	('Invencível RPG', 'invencivel-rpg', 308),
	('Investigar RPG', 'investigar-rpg', 309),
	('Invincible', 'invincible', 310),
	('Ironclaw', 'ironclaw', 311),
	('Ironsworn', 'ironsworn', 312),
	('Ironsworn: Starforged', 'ironsworn-starforged', 313),
	('Jamais Vu', 'jamais-vu', 314),
	('James Bond 007: Role-Playing In Her Majesty''s Secret Service', 'james-bond-007-role-playing-in-her-majestys-secret-service', 315),
	('Jim Henson''s Labyrinth Adventure Game', 'jim-hensons-labyrinth-adventure-game', 316),
	('Justice League Unlimited RPG', 'justice-league-unlimited-rpg', 317),
	('Kalymba RPG', 'kalymba-rpg', 318),
	('Karyu Densetsu', 'karyu-densetsu', 319),
	('Katana-Ra', 'katana-ra', 320),
	('Kids on Bikes', 'kids-on-bikes', 321),
	('Kids on Brooms', 'kids-on-brooms', 322),
	('Kilombo RPG', 'kilombo-rpg', 323),
	('King Arthur Pendragon RPG', 'king-arthur-pendragon-rpg', 324),
	('Kingdom 2nd Edition', 'kingdom-2nd-edition', 325),
	('Knave', 'knave', 326),
	('Knave 2e', 'knave-2e', 327),
	('Kobolds Ate My Baby!', 'kobolds-ate-my-baby', 328),
	('KULT', 'kult', 329),
	('Kuro', 'kuro', 330),
	('Lady Blackbird', 'lady-blackbird', 331),
	('Lancer', 'lancer', 332),
	('Lancer Battlegroup', 'lancer-battlegroup', 333),
	('Land of Eem', 'land-of-eem', 334),
	('LARP', 'larp', 335),
	('Lasers & Feelings', 'lasers-e-feelings', 336),
	('Legacy: Life Among the Ruins 2nd Edition', 'legacy-life-among-the-ruins-2nd-edition', 337),
	('Legend in the Mist', 'legend-in-the-mist', 338),
	('Legend of the Five Rings 4th Edition', 'legend-of-the-five-rings-4th-edition', 339),
	('Legend of the Five Rings 5th Edition', 'legend-of-the-five-rings-5th-edition', 340),
	('Legend of the Five Rings First Edition', 'legend-of-the-five-rings-first-edition', 341),
	('Legião: A Era da Desolação', 'legiao-a-era-da-desolacao', 342),
	('Lendas de Odrite', 'lendas-de-odrite', 343),
	('Level Up Advanced 5th Edition', 'level-up-advanced-5th-edition', 344),
	('Libra RPG', 'libra-rpg', 345),
	('Lições RPG', 'licoes-rpg', 346),
	('Liminal', 'liminal', 347),
	('Liminal Horror', 'liminal-horror', 348),
	('Lion & Dragon', 'lion-e-dragon', 349),
	('Little Fears', 'little-fears', 350),
	('Lobisomem: O Apocalipse - Edição 20 anos', 'lobisomem-o-apocalipse-edicao-20-anos', 351),
	('Lobisomem: O Apocalipse 5ª Edição', 'lobisomem-o-apocalipse-5-edicao', 352),
	('Lobisomem: Os Destituídos', 'lobisomem-os-destituidos', 353),
	('Lobisomen: o Apocalipse', 'lobisomen-o-apocalipse', 354),
	('Low Fantasy Gaming', 'low-fantasy-gaming', 355),
	('LUMEN', 'lumen', 356),
	('Lunatar', 'lunatar', 357),
	('Lunatar RPG', 'lunatar-rpg', 358),
	('Mage the Ascension 20th Anniversary', 'mage-the-ascension-20th-anniversary', 359),
	('Mage: The Awakening 2nd Edition', 'mage-the-awakening-2nd-edition', 360),
	('Mage: The Sorcerers Crusade', 'mage-the-sorcerers-crusade', 361),
	('Malditos Goblins', 'malditos-goblins', 362),
	('Mares do Sertão RPG', 'mares-do-sertao-rpg', 363),
	('Mark of the Odd', 'mark-of-the-odd', 364),
	('Marvel Heroic Roleplaying', 'marvel-heroic-roleplaying', 365),
	('Marvel Multiverse Role-Playing Game', 'marvel-multiverse-role-playing-game', 366),
	('Marvel Super-Heroes FASERIP', 'marvel-super-heroes-faserip', 367),
	('Masks: A New Generation', 'masks-a-new-generation', 368),
	('Mass Effect 5e', 'mass-effect-5e', 369),
	('Mausritter', 'mausritter', 370),
	('Maytréia', 'maytreia', 371),
	('Melodia Perdida', 'melodia-perdida', 372),
	('Melted Lands', 'melted-lands', 373),
	('Memento Mori', 'memento-mori', 374),
	('Metamorphosis Alpha', 'metamorphosis-alpha', 375),
	('Microscope', 'microscope', 376),
	('Middle-earth Role Playing - MERP', 'middle-earth-role-playing-merp', 377),
	('Mighty Blade', 'mighty-blade', 378),
	('Millennia', 'millennia', 379),
	('Mistborn Adventure Game', 'mistborn-adventure-game', 380),
	('Modern AGE RPG', 'modern-age-rpg', 381),
	('Mojubá', 'mojuba', 382),
	('Monad Echo', 'monad-echo', 383),
	('Mono RPG', 'mono-rpg', 384),
	('Monster of the Week', 'monster-of-the-week', 385),
	('MonsterHearts 2', 'monsterhearts-2', 386),
	('Monsters and Other Childish Things', 'monsters-and-other-childish-things', 387),
	('Monty Python''s Supplemental Educational Resource Materials for Pre- or Inter-Course Study', 'monty-pythons-supplemental-educational-resource-materials-fo', 388),
	('MOONGRAVE', 'moongrave', 389),
	('Moonlight on Roseville Beach', 'moonlight-on-roseville-beach', 390),
	('Mörk Borg', 'mork-borg', 391),
	('Mothership', 'mothership', 392),
	('Motim', 'motim', 393),
	('Mouse Guard RPG', 'mouse-guard-rpg', 394),
	('Museu Encantado', 'museu-encantado', 395),
	('Mutant Chronicles', 'mutant-chronicles', 396),
	('Mutant Crawl Classics', 'mutant-crawl-classics', 397),
	('Mutant: Year Zero', 'mutant-year-zero', 398),
	('Mutants & Masterminds', 'mutants-e-masterminds', 399),
	('Mutants and Masterminds (3e)', 'mutants-and-masterminds-3e', 400),
	('My Little Pony Roleplaying Game', 'my-little-pony-roleplaying-game', 401),
	('Mythic Bastionland', 'mythic-bastionland', 402),
	('Mythras', 'mythras', 403),
	('Mythras Imperative', 'mythras-imperative', 404),
	('Mythwoven', 'mythwoven', 405),
	('Nebula', 'nebula', 406),
	('Nemesis', 'nemesis', 407),
	('Nessus', 'nessus', 408),
	('Never Going Home', 'never-going-home', 409),
	('Never Stop Blowing Up', 'never-stop-blowing-up', 410),
	('Nibiru', 'nibiru', 411),
	('Night''s Black Agents', 'nights-black-agents', 412),
	('Nimble', 'nimble', 413),
	('Nobilis: the Game of Sovereign Powers (2002 Edition)', 'nobilis-the-game-of-sovereign-powers-2002-edition', 414),
	('Notequest', 'notequest', 415),
	('Numenera', 'numenera', 416),
	('O Desafio dos Bandeirantes', 'o-desafio-dos-bandeirantes', 417),
	('O Legado', 'o-legado', 418),
	('O Rei Amarelo', 'o-rei-amarelo', 419),
	('O Som das Seis', 'o-som-das-seis', 420),
	('Oblívio RPG', 'oblivio-rpg', 421),
	('Odyssey of the Dragonlords', 'odyssey-of-the-dragonlords', 422),
	('Oeste Sombrio', 'oeste-sombrio', 423),
	('Old Dragon', 'old-dragon', 424),
	('Old Dragon 2ª Edição', 'old-dragon-2-edicao', 425),
	('Old Gods of Appalachia', 'old-gods-of-appalachia', 426),
	('Old-School Essentials', 'old-school-essentials', 427),
	('One Shot RPG System', 'one-shot-rpg-system', 428),
	('Only War RPG', 'only-war-rpg', 429),
	('Opera RPG', 'opera-rpg', 430),
	('Orbital Blues', 'orbital-blues', 431),
	('Ordem Paranormal', 'ordem-paranormal', 432),
	('Ordem Paranormal 2', 'ordem-paranormal-2', 433),
	('OSRIC', 'osric', 434),
	('Outcast Silver Raiders', 'outcast-silver-raiders', 435),
	('Outgunned', 'outgunned', 436),
	('Outro', 'outro', 437),
	('Pacha', 'pacha', 438),
	('Paleomythic', 'paleomythic', 439),
	('Palladium', 'palladium', 440),
	('Pampa RPG', 'pampa-rpg', 441),
	('PARA', 'para', 442),
	('Paranoia', 'paranoia', 443),
	('Pasión de Las Pasiones', 'pasion-de-las-pasiones', 444),
	('Passing', 'passing', 445),
	('Pathfinder 1e', 'pathfinder-1e', 446),
	('Pathfinder 2e', 'pathfinder-2e', 447),
	('Pathfinder Remaster', 'pathfinder-remaster', 448),
	('Pathways To Adventure', 'pathways-to-adventure', 449),
	('Patrulha da Noite', 'patrulha-da-noite', 450),
	('PBTA (Powered By The Apocalypse)', 'pbta-powered-by-the-apocalypse', 451),
	('Pelúcias e Pavores', 'pelucias-e-pavores', 452),
	('Pendragon 6th Edition', 'pendragon-6th-edition', 453),
	('Pequeños Detectives de Monstruos', 'pequenos-detectives-de-monstruos', 454),
	('Perigos & Princesas', 'perigos-e-princesas', 455),
	('Perils & Princesses', 'perils-e-princesses', 456),
	('Phantasy Star Tabletop RPG', 'phantasy-star-tabletop-rpg', 457),
	('Pirate Borg', 'pirate-borg', 458),
	('Playtest', 'playtest', 459),
	('Playtest Game', 'playtest-game', 460),
	('Point System Gaming', 'point-system-gaming', 461),
	('Pokemon Tabletop Adventures 3', 'pokemon-tabletop-adventures-3', 462),
	('Pokemon Tabletop United', 'pokemon-tabletop-united', 463),
	('Pokemon: The Roleplaying Game', 'pokemon-the-roleplaying-game', 464),
	('Pólvora e Fábulas', 'polvora-e-fabulas', 465),
	('Polymorph', 'polymorph', 466),
	('Power Rangers Roleplaying Game', 'power-rangers-roleplaying-game', 467),
	('Power-Up! Universe', 'power-up-universe', 468),
	('Prowlers & Paragons', 'prowlers-e-paragons', 469),
	('Psi*Run', 'psi-run', 470),
	('Public Access', 'public-access', 471),
	('Pulp Cthulhu', 'pulp-cthulhu', 472),
	('Punk Apocalyptic', 'punk-apocalyptic', 473),
	('Quest', 'quest', 474),
	('Rapscallion', 'rapscallion', 475),
	('Rastro de Cthulhu', 'rastro-de-cthulhu', 476),
	('Realms of Pugmire', 'realms-of-pugmire', 477),
	('Red Markets', 'red-markets', 478),
	('Reign', 'reign', 479),
	('Relatos do Grande Irmão', 'relatos-do-grande-irmao', 480),
	('Retropunk RPG', 'retropunk-rpg', 481),
	('Rifts', 'rifts', 482),
	('Righteous Blood, Ruthless Blades', 'righteous-blood-ruthless-blades', 483),
	('Risus: The Anything RPG', 'risus-the-anything-rpg', 484),
	('Rivers of London', 'rivers-of-london', 485),
	('Rogue Trader', 'rogue-trader', 486),
	('Rolemaster', 'rolemaster', 487),
	('Roll for Shoes', 'roll-for-shoes', 488),
	('Ronin', 'ronin', 489),
	('Root: The Roleplaying Game', 'root-the-roleplaying-game', 490),
	('Runarcana', 'runarcana', 491),
	('RuneQuest: Roleplaying in Glorantha', 'runequest-roleplaying-in-glorantha', 492),
	('Rust and Redemption', 'rust-and-redemption', 493),
	('Ryne', 'ryne', 494),
	('Ryuutama', 'ryuutama', 495),
	('S5E: Superheroic Roleplaying', 's5e-superheroic-roleplaying', 496),
	('Sacramento RPG', 'sacramento-rpg', 497),
	('Salvage Union', 'salvage-union', 498),
	('Sátiro de Ouro', 'satiro-de-ouro', 499),
	('Savage Worlds', 'savage-worlds', 500),
	('Scarred Lands', 'scarred-lands', 501),
	('Scion 1e', 'scion-1e', 502),
	('Scion 2e', 'scion-2e', 503),
	('Scum and Villainy', 'scum-and-villainy', 504),
	('Seeds of Wars', 'seeds-of-wars', 505),
	('Seminar', 'seminar', 506),
	('Sensōji TTRPG', 'sensoji-ttrpg', 507),
	('Sentinel Comics', 'sentinel-comics', 508),
	('Serenity RPG', 'serenity-rpg', 509),
	('Shadow of the Demon Lord', 'shadow-of-the-demon-lord', 510),
	('Shadow of the Weird Wizard', 'shadow-of-the-weird-wizard', 511),
	('Shadowdark RPG', 'shadowdark-rpg', 512),
	('Shadowrun', 'shadowrun', 513),
	('Sherlock Holmes RPG', 'sherlock-holmes-rpg', 514),
	('Sigmata', 'sigmata', 515),
	('Silhouette', 'silhouette', 516),
	('Sistema Daemon', 'sistema-daemon', 517),
	('Sistema Dharma', 'sistema-dharma', 518),
	('Sistema Próprio', 'sistema-proprio', 519),
	('Skyfall RPG', 'skyfall-rpg', 520),
	('Slav Borg', 'slav-borg', 521),
	('SLAYERS', 'slayers', 522),
	('Slugblaster', 'slugblaster', 523),
	('Solaria', 'solaria', 524),
	('Sorcerer', 'sorcerer', 525),
	('Space Dragon', 'space-dragon', 526),
	('Spectaculars', 'spectaculars', 527),
	('Spindlewheel', 'spindlewheel', 528),
	('Spire: The City Must Fall RPG', 'spire-the-city-must-fall-rpg', 529),
	('Stalker 2ª Edição', 'stalker-2-edicao', 530),
	('Stalker RPG', 'stalker-rpg', 531),
	('Stalwart ''85', 'stalwart-85', 532),
	('Star Borg', 'star-borg', 533),
	('Star Frontiers', 'star-frontiers', 534),
	('Star Trek Adventures', 'star-trek-adventures', 535),
	('Star Trek Adventures - Second Edition', 'star-trek-adventures-second-edition', 536),
	('Star Wars 5e', 'star-wars-5e', 537),
	('Star Wars D6', 'star-wars-d6', 538),
	('Star Wars RPG by Fantasy Flight Games', 'star-wars-rpg-by-fantasy-flight-games', 539),
	('Star Wars: Saga Edition', 'star-wars-saga-edition', 540),
	('Starfinder', 'starfinder', 541),
	('Starfinder 2e', 'starfinder-2e', 542),
	('Stargate SG-1 RPG', 'stargate-sg-1-rpg', 543),
	('Stars Without Numbers (Revised)', 'stars-without-numbers-revised', 544),
	('Steel Hearts', 'steel-hearts', 545),
	('Stewpot', 'stewpot', 546),
	('Storypath', 'storypath', 547),
	('Strain', 'strain', 548),
	('Swords & Wizardry', 'swords-e-wizardry', 549),
	('Symbaroum', 'symbaroum', 550),
	('Synthicide RPG', 'synthicide-rpg', 551),
	('Tagmar', 'tagmar', 552),
	('Tales From the Loop', 'tales-from-the-loop', 553),
	('Tales of Menace & Mystery', 'tales-of-menace-e-mystery', 554),
	('Tales of the Valiant', 'tales-of-the-valiant', 555),
	('Talislanta', 'talislanta', 556),
	('Teatime Adventures', 'teatime-adventures', 557),
	('Technoir', 'technoir', 558),
	('Teens in Space', 'teens-in-space', 559),
	('Ten Candles', 'ten-candles', 560),
	('Tenebra', 'tenebra', 561),
	('Terra Devastada', 'terra-devastada', 562),
	('Terravysta RPG', 'terravysta-rpg', 563),
	('The Beast', 'the-beast', 564),
	('The Between', 'the-between', 565),
	('The Between: Ghosts of El Paso', 'the-between-ghosts-of-el-paso', 566),
	('The Black Hack 2e', 'the-black-hack-2e', 567),
	('The Burning Wheel', 'the-burning-wheel', 568),
	('The Dark Eye', 'the-dark-eye', 569),
	('The Darkest House', 'the-darkest-house', 570),
	('The Dee Sanction', 'the-dee-sanction', 571),
	('The Dresden Files RPG', 'the-dresden-files-rpg', 572),
	('The Electric State Roleplaying Game', 'the-electric-state-roleplaying-game', 573),
	('The Expanse RPG', 'the-expanse-rpg', 574),
	('The Fifth Season', 'the-fifth-season', 575),
	('The Grimoire of Heart', 'the-grimoire-of-heart', 576),
	('The Happiest Apocalipse on Earth', 'the-happiest-apocalipse-on-earth', 577),
	('The Hero''s Journey', 'the-heros-journey', 578),
	('The Job', 'the-job', 579),
	('The Land Roleplaying System', 'the-land-roleplaying-system', 580),
	('The Lord of the Rings™ Roleplaying 5e', 'the-lord-of-the-rings-roleplaying-5e', 581),
	('The Magnus Archives', 'the-magnus-archives', 582),
	('The Mecha Hack', 'the-mecha-hack', 583),
	('The Mutant Epoch', 'the-mutant-epoch', 584),
	('The One Ring 1e', 'the-one-ring-1e', 585),
	('The One Ring 2e', 'the-one-ring-2e', 586),
	('The Quiet Year', 'the-quiet-year', 587),
	('The Silt Verses', 'the-silt-verses', 588),
	('The Sprawl', 'the-sprawl', 589),
	('The Spy Game', 'the-spy-game', 590),
	('The Strange', 'the-strange', 591),
	('The Supernatural Role Playing Game', 'the-supernatural-role-playing-game', 592),
	('The Sword, The Crown, and The Unspeakable Power', 'the-sword-the-crown-and-the-unspeakable-power', 593),
	('The Ultimate Micro-RPG Book', 'the-ultimate-micro-rpg-book', 594),
	('The Veil', 'the-veil', 595),
	('The Walking Dead Universe Roleplaying Game', 'the-walking-dead-universe-roleplaying-game', 596),
	('The Wildsea', 'the-wildsea', 597),
	('The Witch is Dead', 'the-witch-is-dead', 598),
	('The Witcher TTRPG', 'the-witcher-ttrpg', 599),
	('They Came From', 'they-came-from', 600),
	('They Came from Beyond the Grave!', 'they-came-from-beyond-the-grave', 601),
	('Things from the Flood', 'things-from-the-flood', 602),
	('Thirsty Sword Lesbians', 'thirsty-sword-lesbians', 603),
	('This Discord Has Ghosts in It', 'this-discord-has-ghosts-in-it', 604),
	('Thordezilhas: Sabres & Caravelas', 'thordezilhas-sabres-e-caravelas', 605),
	('Through The Breach', 'through-the-breach', 606),
	('TimeWatch', 'timewatch', 607),
	('Tiny Cthulhu', 'tiny-cthulhu', 608),
	('Tiny Dungeon', 'tiny-dungeon', 609),
	('Tiny Dungeon: Second Edition', 'tiny-dungeon-second-edition', 610),
	('Tiny Supers', 'tiny-supers', 611),
	('Toon Roleplaying Game', 'toon-roleplaying-game', 612),
	('Torg', 'torg', 613),
	('Torg Eternity', 'torg-eternity', 614),
	('Tormenta Alpha', 'tormenta-alpha', 615),
	('Tormenta RPG (2010)', 'tormenta-rpg-2010', 616),
	('Tormenta Terceira Edição (Daemon)', 'tormenta-terceira-edicao-daemon', 617),
	('Trail of Cthulhu', 'trail-of-cthulhu', 618),
	('Transformers Roleplaying Game', 'transformers-roleplaying-game', 619),
	('Traveller', 'traveller', 620),
	('tremulus', 'tremulus', 621),
	('Trevas', 'trevas', 622),
	('Triangle Agency', 'triangle-agency', 623),
	('Trinity Continuum', 'trinity-continuum', 624),
	('Trivia', 'trivia', 625),
	('Troika!', 'troika', 626),
	('Trophy Dark', 'trophy-dark', 627),
	('Tunnels & Trolls', 'tunnels-e-trolls', 628),
	('Twilight 2000', 'twilight-2000', 629),
	('Ultraviolet Grasslands', 'ultraviolet-grasslands', 630),
	('Unbelievably Simple Role-playing', 'unbelievably-simple-role-playing', 631),
	('Uncharted Worlds', 'uncharted-worlds', 632),
	('Unknown Armies 2e', 'unknown-armies-2e', 633),
	('Unknown Armies 3e', 'unknown-armies-3e', 634),
	('Urban Shadows 1e', 'urban-shadows-1e', 635),
	('Urban Shadows 2e', 'urban-shadows-2e', 636),
	('Urbana Bellica', 'urbana-bellica', 637),
	('Utopia', 'utopia', 638),
	('Vaesen', 'vaesen', 639),
	('Vagabond', 'vagabond', 640),
	('Valor: the Heroic Roleplay System', 'valor-the-heroic-roleplay-system', 641),
	('Vampiro: A Idade das Trevas', 'vampiro-a-idade-das-trevas', 642),
	('Vampiro: A Máscara - Edição de 20º Aniversário', 'vampiro-a-mascara-edicao-de-20-aniversario', 643),
	('Vampiro: A Máscara 2ª Edição', 'vampiro-a-mascara-2-edicao', 644),
	('Vampiro: A Máscara 5ª Edição', 'vampiro-a-mascara-5-edicao', 645),
	('Vampiro: A Máscara 6ª Edição', 'vampiro-a-mascara-6-edicao', 646),
	('Vampiro: A Máscara Edição Revisada', 'vampiro-a-mascara-edicao-revisada', 647),
	('Vampiro: O Requiem 2ª Edição', 'vampiro-o-requiem-2-edicao', 648),
	('Vaults of Vaarn', 'vaults-of-vaarn', 649),
	('Verbum', 'verbum', 650),
	('Vileborn RPG', 'vileborn-rpg', 651),
	('Violentina', 'violentina', 652),
	('Wanderhome', 'wanderhome', 653),
	('Warbirds', 'warbirds', 654),
	('Warhammer 40,000 Imperium Maledictum', 'warhammer-40-000-imperium-maledictum', 655),
	('Warhammer 40,000 Roleplay', 'warhammer-40-000-roleplay', 656),
	('Warhammer 40,000 Wrath & Glory', 'warhammer-40-000-wrath-e-glory', 657),
	('Warhammer Age of Sigmar Soulbound', 'warhammer-age-of-sigmar-soulbound', 658),
	('Warhammer Fantasy Roleplay', 'warhammer-fantasy-roleplay', 659),
	('Warhammer: the Old World Roleplaying Game', 'warhammer-the-old-world-roleplaying-game', 660),
	('Warlock!', 'warlock', 661),
	('Warped', 'warped', 662),
	('Warrenguard', 'warrenguard', 663),
	('Weird Heroes of Public Access', 'weird-heroes-of-public-access', 664),
	('Welcome to Dolmenwood', 'welcome-to-dolmenwood', 665),
	('Welcome to Night Vale Roleplaying Game', 'welcome-to-night-vale-roleplaying-game', 666),
	('Wild Talents', 'wild-talents', 667),
	('Wilderfeast RPG', 'wilderfeast-rpg', 668),
	('Workshop', 'workshop', 669),
	('World of Darkness', 'world-of-darkness', 670),
	('World Wide Wrestling 2e', 'world-wide-wrestling-2e', 671),
	('Worlds without Number', 'worlds-without-number', 672),
	('Wraith: The Oblivion 20th Anniversary Edition', 'wraith-the-oblivion-20th-anniversary-edition', 673),
	('Xas Irkalla', 'xas-irkalla', 674),
	('Xenoscape', 'xenoscape', 675),
	('Yazeba''s Bed & Breakfast', 'yazebas-bed-e-breakfast', 676),
	('Yggdrasill', 'yggdrasill', 677),
	('Ymortis', 'ymortis', 678),
	('Z-LAND', 'z-land', 679),
	('Zafir: Tactical Roleplaying Game', 'zafir-tactical-roleplaying-game', 680),
	('Zansara', 'zansara', 681),
	('Zweihander', 'zweihander', 682)
ON CONFLICT ("slug") DO NOTHING;--> statement-breakpoint
-- Tables now point at a system instead of holding its name: add the column empty, fill it from the
-- old text (a name that is not in the list becomes "Outro"), then require it.
ALTER TABLE "game_tables" ADD COLUMN "system_id" uuid;--> statement-breakpoint
UPDATE "game_tables" SET "system_id" = COALESCE(
	(SELECT "id" FROM "systems" WHERE "name" = "game_tables"."system"),
	(SELECT "id" FROM "systems" WHERE "slug" = 'outro')
);--> statement-breakpoint
ALTER TABLE "game_tables" ALTER COLUMN "system_id" SET NOT NULL;--> statement-breakpoint
ALTER TABLE "game_tables" ADD CONSTRAINT "game_tables_system_id_systems_id_fk" FOREIGN KEY ("system_id") REFERENCES "public"."systems"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "game_tables_system_id_idx" ON "game_tables" USING btree ("system_id");