// Generated by `pnpm changelog` from src/content/changelog/. Do not edit by hand.
export const ENTRY_FILES: Record<string, string> = {
  '2026-09-29-lancamento.md':
    '---\ndate: 2026-09-29\ntitle: Lançamento da plataforma\n---\n\nA Mesa Aberta está no ar. Mestres abrem mesas de RPG, jogadores encontram uma e pegam a vaga.\n',
  '2026-09-30-minhas-mesas-celular.md':
    '---\ndate: 2026-09-30\ntitle: Minhas mesas no celular em abas\n---\n\nNo celular, Minhas mesas agora separa as mesas que você joga das que você mestra em duas abas.\n\n## Alterado\n\n- No celular, "Jogando" e "Mestrando" viram abas no topo de Minhas mesas, cada uma com o número de mesas. Se você só mestra, a página já abre em "Mestrando". O botão "Ver o pedido" do aviso de pedidos de vaga leva direto à mesa, na aba "Mestrando".\n- No celular, a lista de participantes de cada mesa que você mestra fica atrás do botão "Participantes (N)". Só a da primeira mesa começa aberta. Os pedidos de vaga continuam sempre à vista.\n',
  '2026-09-30-recorte-de-imagens.md':
    '---\ndate: 2026-09-30\ntitle: Recorte de fotos e capas, e contagens no singular\n---\n\nAo escolher uma foto de perfil ou a capa de uma mesa, você agora enquadra a imagem antes de enviar.\n\n## Adicionado\n\n- Foto de perfil e capa de mesa abrem um recorte ao escolher o arquivo: arraste para mover, aproxime com os botões, a roda do mouse ou o gesto de pinça, ou use as setas e as teclas + e − do teclado. Uma prévia mostra como a imagem vai aparecer, e só o recorte é enviado.\n\n## Alterado\n\n- Os contadores agora usam a forma certa para zero e para um: "nenhuma mesa", "1 mesa", "2 mesas", e o mesmo para vagas, avaliações e contas.\n',
};
