// Generated by `pnpm changelog` from src/content/changelog/. Do not edit by hand.
export const ENTRY_FILES: Record<string, string> = {
  '2026-09-29-lancamento.md':
    '---\ndate: 2026-09-29\ntitle: Lançamento da plataforma\n---\n\nA Mesa Aberta está no ar. Mestres abrem mesas de RPG, jogadores encontram uma e pegam a vaga.\n',
};
