// Bundles the changelog entries (src/content/changelog/*.md) into one TypeScript module, so the
// site and the Cron Trigger's Worker (which wrangler bundles without Vite) read the same entries.
// Run `pnpm changelog` after adding or editing an entry; a unit test fails while it is stale.
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';

const dir = 'src/content/changelog';
const out = 'src/lib/changelog/entries.generated.ts';

const files = readdirSync(dir)
  .filter((name) => name.endsWith('.md'))
  .sort();
const map = Object.fromEntries(files.map((name) => [name, readFileSync(`${dir}/${name}`, 'utf8')]));

const source = `// Generated by \`pnpm changelog\` from ${dir}/. Do not edit by hand.
export const ENTRY_FILES: Record<string, string> = ${JSON.stringify(map, null, 2)};
`;
const options = { ...(await resolveConfig(out)), filepath: out };
writeFileSync(out, await format(source, options));
console.log(`changelog: ${files.length} entries → ${out}`);
