// Copies the drawings of the icons listed in src/lib/icons/names.ts from the Lucide set
// (@iconify-json/lucide) into one small module, so the bundle carries only the icons in use and the
// page never asks Iconify's API for one. Run `pnpm icons` after changing the list; a unit test
// fails while the module is stale.
import { writeFileSync } from 'node:fs';
import { format, resolveConfig } from 'prettier';
import { iconData } from '../src/lib/icons/source.ts';
import { ICON_NAMES } from '../src/lib/icons/names.ts';

const out = 'src/lib/icons/lucide.generated.ts';

const source = `// Generated by \`pnpm icons\` from @iconify-json/lucide. Do not edit by hand.
import type { IconifyIcon } from '@iconify/types';
import type { IconName } from './names';

export const ICONS: Record<IconName, IconifyIcon> = ${JSON.stringify(iconData(ICON_NAMES), null, 2)};
`;
const options = { ...(await resolveConfig(out)), filepath: out };
writeFileSync(out, await format(source, options));
console.log(`icons: ${ICON_NAMES.length} icons → ${out}`);
