// Expand the CSS geometry shipped with the individual Iconify components into ordinary SVG
// attributes. This keeps their imports while rendering offline, including browsers without CSS d.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

const registry = readFileSync('src/lib/icons/registry.ts', 'utf8');
const drawings = new Map<string, { body: string; width: number; height: number }>();
const attributes = new Set([
  'fill',
  'fill-rule',
  'clip-rule',
  'fill-opacity',
  'opacity',
  'stroke',
  'stroke-linecap',
  'stroke-linejoin',
  'stroke-miterlimit',
  'stroke-width',
  'd',
  'width',
  'height',
  'x',
  'y',
  'rx',
  'ry',
  'cx',
  'cy',
  'r',
]);
const escape = (value: string) => value.replaceAll('&', '&amp;').replaceAll('"', '&quot;');

for (const match of registry.matchAll(/import (\w+) from '@iconify-svelte\/([^/]+)\/([^']+)';/g)) {
  const [, component, collection, icon] = match;
  const root = resolve('node_modules', '@iconify-svelte', collection);
  const pkg = JSON.parse(readFileSync(resolve(root, 'package.json'), 'utf8'));
  const file = resolve(root, pkg.exports[`./${icon}`].svelte);
  const source = readFileSync(file, 'utf8');
  const viewBox = JSON.parse(source.match(/const viewBox = (\{.*?\});/)![1]);
  let body = source.match(/const content = `([^`]+)`;/)![1];
  const rules = new Map<string, string>();
  for (const css of source.matchAll(/import '([^']+\.css)';/g)) {
    const content = readFileSync(resolve(dirname(file), css[1]), 'utf8');
    for (const rule of content.matchAll(/\.([\w-]+)\s*\{([^}]+)\}/g)) {
      const values = [...rule[2].matchAll(/([\w-]+):\s*([^;]+);/g)].map((declaration) => {
        const [, property, original] = declaration;
        if (!attributes.has(property)) throw new Error(`Unsupported SVG property: ${property}`);
        let value = original.trim();
        if (property === 'd') value = JSON.parse(value.slice(5, -1));
        else value = value.replace(/^var\([^,]+,\s*([^)]+)\)$/, '$1').replace(/px$/, '');
        return `${property}="${escape(value)}"`;
      });
      rules.set(rule[1], values.join(' '));
    }
  }
  body = body.replace(/class="([^"]+)"/g, (_, classes: string) =>
    classes
      .split(/\s+/)
      .map((name) => {
        const attrs = rules.get(name);
        if (attrs === undefined) throw new Error(`Missing SVG rule: ${name}`);
        return attrs;
      })
      .join(' '),
  );
  drawings.set(component, { body, ...viewBox });
}

const data = Object.fromEntries(
  [
    ...registry.split('export const ICONS = {')[1].matchAll(/\s*(?:'([^']+)'|([\w-]+)):\s*(\w+),/g),
  ].map(([, quoted, bare, component]) => {
    const drawing = drawings.get(component);
    if (!drawing) throw new Error(`Missing drawing: ${component}`);
    return [quoted ?? bare, drawing];
  }),
);
const out = 'src/lib/icons/drawings.generated.ts';
const source = `// Generated by bun run icons from the installed individual Iconify packages. Do not edit.\nimport type { IconName } from './names';\n\nexport const DRAWINGS = ${JSON.stringify(data)} satisfies Record<IconName, { body: string; width: number; height: number }>;\n`;
writeFileSync(out, await format(source, { ...(await resolveConfig(out)), filepath: out }));
console.log(`icons: ${drawings.size} local SVG drawings`);
